'use client';
import {libraryFetch as fetch} from './bridge-client';
import {useEffect,useRef,useState} from 'react';
import Watch from './NoirPlayer';
import PlaybackAccount from './PlaybackAccount';
import Carousel from './Carousel';
import {rankedLibrary} from './LibrarySearch';
import {Play,Search,LockKeyhole,RefreshCw,Settings2,X,Film,ArrowUpRight,SkipBack,SkipForward,Maximize,Pause,Library} from 'lucide-react';
type Video={id:string;title:string;description:string;thumbnail:string;published:string;duration:number;privacy:string;definition:string;position:number};
type Data={videos:Video[];count:number;total:number;connected:boolean;complete:boolean;channel?:string;synced?:string;cloudflareConfigured?:boolean};
const empty:Data={videos:[],count:0,total:0,connected:false,complete:false};
const time=(s:number)=>{s=Math.floor(s||0);return s>=3600?Math.floor(s/3600)+':'+String(Math.floor(s/60)%60).padStart(2,'0')+':'+String(s%60).padStart(2,'0'):Math.floor(s/60)+':'+String(s%60).padStart(2,'0');};
async function action(body:unknown){const r=await fetch('/api/library',{method:'POST',headers:{'Content-Type':'application/json','X-Noir-Request':'1'},body:JSON.stringify(body)});const j:any=await r.json();if(!r.ok)throw new Error(j.error||'Please try again.');return j;}
export default function Cinema(){
 const [data,setData]=useState(empty),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[sort,setSort]=useState('newest'),[offset,setOffset]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState(''),[syncing,setSyncing]=useState(false),[checked,setChecked]=useState(0),[watch,setWatch]=useState<Video|null>(null),[settingsOpen,setSettingsOpen]=useState(false),[busy,setBusy]=useState(false),[refresh,setRefresh]=useState(0);
 const [home,setHome]=useState<{recent:Video[];most:Video[];continue:Video[]}>({recent:[],most:[],continue:[]});const [homeError,setHomeError]=useState('');
 const initialSyncStarted=useRef(false);
 useEffect(()=>{if(!data.connected)return;const controller=new AbortController();fetch('/api/library?view=home',{signal:controller.signal}).then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j.error||'Home rows could not load.');if(!j.home)throw new Error('Home rows need the updated library backend.');return j.home;}).then(j=>{setHome(j);setHomeError('');}).catch(e=>{if(e.name!=='AbortError')setHomeError(e.message);});return()=>controller.abort();},[data.connected,refresh]);
 const settingsDialog=useRef<HTMLDialogElement>(null),search=useRef<HTMLInputElement>(null);
 useEffect(()=>{const controller=new AbortController();const timeout=setTimeout(()=>{setLoading(true);rankedLibrary(query,filter,sort,offset,controller.signal,fetch).then(j=>{setData(j);}).catch(e=>{if(e.name!=='AbortError')setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});},query?250:0);return()=>{clearTimeout(timeout);controller.abort();};},[query,filter,sort,offset,refresh]);
 useEffect(()=>{if(settingsOpen)settingsDialog.current?.showModal();else settingsDialog.current?.close();},[settingsOpen]);
 useEffect(()=>{const handler=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();search.current?.focus();}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);},[]);
 useEffect(()=>{if(data.connected&&!data.complete&&!initialSyncStarted.current){initialSyncStarted.current=true;void sync();}},[data.connected,data.complete]);
 async function sync(){setSyncing(true);setError('');setChecked(0);try{let complete=false;while(!complete){const r=await action({action:'sync'});setChecked(n=>n+r.processed);complete=r.complete;setRefresh(n=>n+1);}}catch(e){setError((e as Error).message);}finally{setSyncing(false);setRefresh(n=>n+1);}}
 function choose(value:string){setQuery('');setFilter(value);setOffset(0);}
 function goHome(){setQuery('');setFilter('all');setSort('newest');setOffset(0);window.scrollTo({top:0,behavior:'smooth'});}
 const featured=data.videos[0];
 return <main><header className="header"><a className="brand" href="./" onClick={e=>{e.preventDefault();goHome();}}><span className="brand-icon"><Play size={15} fill="currentColor"/></span>NOIR<span className="brand-sub">PRIVATE CINEMA</span></a><nav aria-label="Main navigation"><button onClick={goHome}>Home</button><button className={filter==='all'?'active':''} onClick={()=>choose('all')}>Library</button><button className={filter==='continue'?'active':''} onClick={()=>choose('continue')}>Continue watching</button></nav><div className="account"><span><LockKeyhole size={13}/> Only you</span><button className="avatar" aria-label="Connection settings" onClick={()=>setSettingsOpen(true)}>{data.channel?.[0]?.toUpperCase()||'N'}</button></div></header><section className="library-bar"><div><span className="eyebrow">THE PERSONAL COLLECTION</span><h1>Your cinema.</h1></div><div className="tools"><button className="home-shortcut" onClick={goHome}>Home</button><div className="search"><Search size={19}/><input ref={search} placeholder="Search every video…" aria-label="Search all video titles and descriptions" value={query} onChange={e=>{setQuery(e.target.value);setOffset(0);}}/>{query?<button aria-label="Clear search" onClick={()=>{setQuery('');setOffset(0);}}><X size={16}/></button>:<kbd>Ctrl K</kbd>}</div><button className="icon-button" aria-label="Connection settings" onClick={()=>setSettingsOpen(true)}><Settings2 size={20}/></button></div></section>
 {error&&<div className="notice page-notice" role="alert">{error}<button onClick={()=>{setError('');setRefresh(n=>n+1);}}>Retry</button></div>}
 {!loading&&!data.connected?<section className="connect-hero"><div className="empty-emblem"><Film size={48}/></div><span className="eyebrow">YOUR VIDEOS. YOUR SPACE.</span><h2>A home for your<br/><em>private collection.</em></h2><p>Your YouTube connection comes from the private secrets saved in your Cloudflare backend.</p><button className="button primary" onClick={()=>setSettingsOpen(true)}><LockKeyhole size={17}/> Cloudflare connection details</button><small>Private access · Credentials encrypted on the server</small></section>:featured&&!query&&offset===0&&filter==='all'?<section className="hero"><img src={featured.thumbnail} alt=""/><div className="hero-shade"/><div className="hero-content"><span className="eyebrow">LATEST IN YOUR COLLECTION</span><h2>{featured.title}</h2><div className="metadata"><span>{new Date(featured.published).getFullYear()}</span><span>{time(featured.duration)}</span><span className="badge">{featured.privacy}</span><span>YouTube</span></div><p>{featured.description||'Ready when you are.'}</p><button className="button primary" onClick={()=>setWatch(featured)}><Play size={18} fill="currentColor"/>{featured.position>0&&featured.position<featured.duration-15?'Resume watching':'Watch now'}</button></div><div className="hero-caption"><span>01</span> / YOUR COLLECTION</div></section>:null}
 {data.connected&&!query&&filter==='all'&&offset===0&&<div className="home-rows">{homeError&&<p className="notice" role="alert">{homeError}</p>}<Carousel title="Recently added" note="The latest uploads in your private collection" videos={home.recent} open={setWatch}/><Carousel title="Continue watching" note="Pick up where you left off, across NOIR devices" videos={home.continue} open={setWatch}/><Carousel title="Most watched" note="Ranked by YouTube view counts, refreshed when you sync" videos={home.most} open={setWatch}/></div>}
 <section className="collection"><div className="collection-heading"><div className="tabs"><button className={filter==='all'?'selected':''} onClick={()=>choose('all')}>All videos <span>{data.total}</span></button><button className={filter==='private'?'selected':''} onClick={()=>choose('private')}><LockKeyhole size={13}/> Private</button><button className={filter==='continue'?'selected':''} onClick={()=>choose('continue')}>In progress</button></div><div className="collection-actions"><select aria-label="Sort library" value={sort} onChange={e=>{setSort(e.target.value);setOffset(0);}}><option value="newest">Newest first</option><option value="oldest">Oldest first</option><option value="title">Title A–Z</option></select><button disabled={syncing||!data.connected} onClick={sync} className="sync"><RefreshCw size={15} className={syncing?'spinning':''}/>{syncing?'Syncing…':'Sync library'}</button></div></div><div className="collection-status" aria-live="polite"><span>{query?data.count+' results for “'+query+'”':data.channel?data.channel+' · '+data.count+' videos':'Your YouTube uploads will appear here'}</span><span>{syncing?checked+' videos checked':data.connected&&!data.complete?'Initial sync incomplete · Sync library to continue':data.synced?'Synced '+new Date(data.synced).toLocaleString():'Search covers titles and descriptions'}</span></div>
 {loading?<div className="grid" aria-label="Loading videos">{[1,2,3,4].map(n=><div className="skeleton" key={n}/>)}</div>:data.videos.length?<div className="grid">{data.videos.map(v=><button className="video-card" key={v.id} onClick={()=>setWatch(v)}><div className="poster"><img src={v.thumbnail} alt="" loading="lazy"/><span className="card-play"><Play size={24} fill="currentColor"/></span><span className="duration">{time(v.duration)}</span>{v.position>0&&v.position<v.duration-15&&<div className="progress"><span style={{width:Math.min(100,v.position/v.duration*100)+'%'}}/></div>}</div><h3>{v.title}</h3><div className="card-meta"><span>{new Date(v.published).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}</span><span>{v.privacy==='private'&&<LockKeyhole size={11}/>} {v.privacy}</span></div></button>)}</div>:data.connected?<div className="empty-results"><Library size={32}/><h3>{query?'No matching videos':filter==='continue'?'Your next watch starts here':data.complete?'No videos in this view':'Your library is ready to sync'}</h3><p>{query?'Try another title or a word from a description.':filter==='continue'?'Videos you start watching will appear here.':'Sync your uploads to refresh this collection.'}</p></div>:null}
 {data.count>24&&<div className="pagination"><button className="button secondary" disabled={offset===0||loading} onClick={()=>setOffset(n=>Math.max(0,n-24))}>Previous</button><span>{offset+1}–{Math.min(offset+24,data.count)} of {data.count}</span><button className="button secondary" disabled={offset+24>=data.count||loading} onClick={()=>setOffset(n=>n+24)}>Next</button></div>}</section><footer><span className="footer-brand">NOIR</span><span>Your collection. A little closer.</span><span><LockKeyhole size={12}/> Owner-only library · YouTube playback</span></footer>
 <dialog className="settings-dialog" ref={settingsDialog} onCancel={()=>setSettingsOpen(false)}><button className="icon-button close-settings" aria-label="Close settings" onClick={()=>setSettingsOpen(false)}><X/></button><span className="eyebrow"><LockKeyhole size={15}/> PRIVATE CONNECTION</span><h2>Your Cloudflare connection</h2><p>NOIR reads your YouTube credentials from Cloudflare after you unlock your library. No files are needed in this website.</p>{data.connected&&<div className="connection">Connected to {data.channel}</div>}<p>{data.cloudflareConfigured?'Your Cloudflare YouTube secrets are configured.':'One-time setup: save the contents of client_secret.json as CLIENT_SECRET_JSON and token.json as TOKEN_JSON in your Cloudflare Worker’s secrets.'}</p><button className="button primary" disabled={syncing} onClick={()=>{setSettingsOpen(false);setError('');setRefresh(n=>n+1);}}>Refresh connection</button><p className="quality-note">The initial library sync starts automatically when the connection is ready. You can use Sync library to refresh your uploads later.</p><PlaybackAccount/></dialog>
 {watch&&<Watch key={watch.id} video={watch} close={()=>{setWatch(null);setTimeout(()=>setRefresh(n=>n+1),500);}}/>}</main>;
}


