'use client';
import {libraryFetch as fetch,BACKEND} from './bridge-client';
import {useEffect,useRef,useState} from 'react';
import {Play,Search,LockKeyhole,RefreshCw,Settings2,X,Film,ArrowUpRight,SkipBack,SkipForward,Maximize,Pause,Library} from 'lucide-react';
type Video={id:string;title:string;description:string;thumbnail:string;published:string;duration:number;privacy:string;definition:string;position:number};
type Data={videos:Video[];count:number;total:number;connected:boolean;complete:boolean;channel?:string;synced?:string};
const empty:Data={videos:[],count:0,total:0,connected:false,complete:false};
const time=(s:number)=>{s=Math.floor(s||0);return s>=3600?Math.floor(s/3600)+':'+String(Math.floor(s/60)%60).padStart(2,'0')+':'+String(s%60).padStart(2,'0'):Math.floor(s/60)+':'+String(s%60).padStart(2,'0');};
async function action(body:unknown){const r=await fetch('/api/library',{method:'POST',headers:{'Content-Type':'application/json','X-Noir-Request':'1'},body:JSON.stringify(body)});const j:any=await r.json();if(!r.ok)throw new Error(j.error||'Please try again.');return j;}
let ytPromise:Promise<void>|null=null;
function loadYT(){if((window as any).YT?.Player)return Promise.resolve();if(!ytPromise)ytPromise=new Promise((resolve,reject)=>{(window as any).onYouTubeIframeAPIReady=()=>resolve();const s=document.createElement('script');s.src='https://www.youtube.com/iframe_api';s.onerror=()=>{ytPromise=null;reject(new Error('YouTube player could not load.'));};document.head.appendChild(s);});return ytPromise;}
function Watch({video,close}:{video:Video;close:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null),host=useRef<HTMLDivElement>(null),player=useRef<any>(null);const [ready,setReady]=useState(false),[playing,setPlaying]=useState(false),[position,setPosition]=useState(video.position),[error,setError]=useState(''),[rate,setRate]=useState(1),[rates,setRates]=useState<number[]>([1]);
 useEffect(()=>{dialog.current?.showModal();let active=true;let timer:ReturnType<typeof setInterval>;let ticks=0;
 loadYT().then(()=>{if(!active||!host.current)return;const el=document.createElement('div');host.current.appendChild(el);player.current=new (window as any).YT.Player(el,{videoId:video.id,width:'100%',height:'100%',playerVars:{autoplay:1,playsinline:1,rel:0,controls:1,origin:location.origin,start:video.position<video.duration-15?Math.floor(video.position):0},events:{onReady:()=>{if(!active)return;setReady(true);setRates(player.current.getAvailablePlaybackRates());timer=setInterval(()=>{const p=player.current;if(!p?.getCurrentTime)return;const t=p.getCurrentTime();setPosition(t);if(++ticks%15===0&&p.getPlayerState()===1)action({action:'progress',id:video.id,seconds:t}).catch(()=>setError('Playback progress could not be saved.'));},1000);},onStateChange:(e:any)=>{if(active)setPlaying(e.data===1);},onError:(e:any)=>{if(active)setError(e.data===100?'YouTube cannot play this private or unavailable video here. Open it on YouTube while signed in to its owner account.':e.data===101||e.data===150?'Embedding is disabled for this video. You can watch it on YouTube.':'YouTube could not play this video here. Use Watch on YouTube above and select the account that owns the upload.');}}});}).catch(e=>setError(e.message));
 return()=>{active=false;clearInterval(timer);if(player.current?.getCurrentTime){action({action:'progress',id:video.id,seconds:player.current.getCurrentTime()}).catch(()=>{});player.current.destroy();}};},[video]);
 function seek(t:number){player.current?.seekTo(Math.max(0,Math.min(video.duration,t)),true);setPosition(t);}
 return <dialog className="watch-dialog" ref={dialog} onCancel={close}><div className="watch-top"><span className="eyebrow">NOW PLAYING</span><button className="icon-button" onClick={close} aria-label="Close player"><X/></button></div><div className="private-playback-help">{video.privacy === 'private' && <><div><strong>Private YouTube video</strong><p>If this player keeps asking you to sign in, open the video directly on YouTube in this browser. Use the account that owns this upload.</p></div><a className="button primary" href={'https://www.youtube.com/watch?v='+video.id+'&t='+Math.max(0,Math.floor(position))+'s'} target="_blank" rel="noopener noreferrer">Watch on YouTube <ArrowUpRight size={16}/></a></>}</div><div className="screen" ref={host}/><div className="transport"><button disabled={!ready} onClick={()=>playing?player.current.pauseVideo():player.current.playVideo()} aria-label={playing?'Pause':'Play'}>{playing?<Pause/>:<Play/>}</button><button disabled={!ready} onClick={()=>seek(position-10)} aria-label="Back 10 seconds"><SkipBack size={20}/></button><button disabled={!ready} onClick={()=>seek(position+10)} aria-label="Forward 10 seconds"><SkipForward size={20}/></button><span className="time">{time(position)}</span><input aria-label="Seek video" type="range" min={0} max={video.duration||1} value={Math.max(0,Math.min(position,video.duration))} onChange={e=>seek(+e.target.value)} disabled={!ready}/><span className="time">{time(video.duration)}</span><select aria-label="Playback speed" value={rate} disabled={!ready} onChange={e=>{setRate(+e.target.value);player.current.setPlaybackRate(+e.target.value);}}>{rates.map(r=><option key={r} value={r}>{r}×</option>)}</select><button aria-label="Fullscreen cinema" onClick={()=>dialog.current?.requestFullscreen().catch(()=>setError('Use YouTube’s fullscreen control in this browser.'))}><Maximize size={20}/></button></div><div className="watch-content">{error&&<div className="notice" role="alert">{error}</div>}<div className="watch-heading"><div><span className="eyebrow">YOUR LIBRARY · {video.privacy.toUpperCase()}</span><h2>{video.title}</h2></div><a className="button secondary" href={'https://www.youtube.com/watch?v='+video.id+'&t='+Math.max(0,Math.floor(position))+'s'} target="_blank" rel="noreferrer">Open YouTube <ArrowUpRight size={16}/></a></div><p className="quality-note">Select 2160p / 4K in YouTube’s player settings when offered. Available quality depends on the upload, processing, device and connection. Private videos may require viewing on YouTube.</p><p className="description">{video.description||'No description added.'}</p></div></dialog>;
}
export default function Cinema(){
 const [data,setData]=useState(empty),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[sort,setSort]=useState('newest'),[offset,setOffset]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState(''),[syncing,setSyncing]=useState(false),[checked,setChecked]=useState(0),[watch,setWatch]=useState<Video|null>(null),[settingsOpen,setSettingsOpen]=useState(false),[busy,setBusy]=useState(false),[refresh,setRefresh]=useState(0);
 const settingsDialog=useRef<HTMLDialogElement>(null),clientFile=useRef<HTMLInputElement>(null),tokenFile=useRef<HTMLInputElement>(null),search=useRef<HTMLInputElement>(null);
 useEffect(()=>{const controller=new AbortController();const timeout=setTimeout(()=>{setLoading(true);fetch('/api/library?'+new URLSearchParams({q:query,filter,sort,offset:String(offset)}),{signal:controller.signal}).then(async r=>{const j:any=await r.json();if(!r.ok)throw new Error(j.error);return j;}).then(j=>{setData(j);}).catch(e=>{if(e.name!=='AbortError')setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});},query?250:0);return()=>{clearTimeout(timeout);controller.abort();};},[query,filter,sort,offset,refresh]);
 useEffect(()=>{if(settingsOpen)settingsDialog.current?.showModal();else settingsDialog.current?.close();},[settingsOpen]);
 useEffect(()=>{const handler=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();search.current?.focus();}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);},[]);
 async function sync(){setSyncing(true);setError('');setChecked(0);try{let complete=false;while(!complete){const r=await action({action:'sync'});setChecked(n=>n+r.processed);complete=r.complete;setRefresh(n=>n+1);}}catch(e){setError((e as Error).message);}finally{setSyncing(false);setRefresh(n=>n+1);}}
 function choose(value:string){setFilter(value);setOffset(0);}
 const featured=data.videos[0];
 return <main><header className="header"><a className="brand" href="./"><span className="brand-icon"><Play size={15} fill="currentColor"/></span>NOIR<span className="brand-sub">PRIVATE CINEMA</span></a><nav aria-label="Main navigation"><button className={filter==='all'?'active':''} onClick={()=>choose('all')}>Library</button><button className={filter==='continue'?'active':''} onClick={()=>choose('continue')}>Continue watching</button></nav><div className="account"><span><LockKeyhole size={13}/> Only you</span><button className="avatar" aria-label="Connection settings" onClick={()=>setSettingsOpen(true)}>{data.channel?.[0]?.toUpperCase()||'N'}</button></div></header><section className="library-bar"><div><span className="eyebrow">THE PERSONAL COLLECTION</span><h1>Your cinema.</h1></div><div className="tools"><div className="search"><Search size={19}/><input ref={search} placeholder="Search every video…" aria-label="Search all video titles and descriptions" value={query} onChange={e=>{setQuery(e.target.value);setOffset(0);}}/>{query?<button aria-label="Clear search" onClick={()=>{setQuery('');setOffset(0);}}><X size={16}/></button>:<kbd>Ctrl K</kbd>}</div><button className="icon-button" aria-label="Connection settings" onClick={()=>setSettingsOpen(true)}><Settings2 size={20}/></button></div></section>
 {error&&<div className="notice page-notice" role="alert">{error}<button onClick={()=>{setError('');setRefresh(n=>n+1);}}>Retry</button></div>}
 {!loading&&!data.connected?<section className="connect-hero"><div className="empty-emblem"><Film size={48}/></div><span className="eyebrow">YOUR VIDEOS. YOUR SPACE.</span><h2>A home for your<br/><em>private collection.</em></h2><p>Connect YouTube to bring your uploads, original artwork and descriptions into one personal cinema.</p><button className="button primary" onClick={()=>setSettingsOpen(true)}><LockKeyhole size={17}/> Connect your library</button><small>Private access · Credentials encrypted on the server</small></section>:featured&&!query&&offset===0&&filter==='all'?<section className="hero"><img src={featured.thumbnail} alt=""/><div className="hero-shade"/><div className="hero-content"><span className="eyebrow">LATEST IN YOUR COLLECTION</span><h2>{featured.title}</h2><div className="metadata"><span>{new Date(featured.published).getFullYear()}</span><span>{time(featured.duration)}</span><span className="badge">{featured.privacy}</span><span>YouTube</span></div><p>{featured.description||'Ready when you are.'}</p><button className="button primary" onClick={()=>setWatch(featured)}><Play size={18} fill="currentColor"/>{featured.position>0&&featured.position<featured.duration-15?'Resume watching':'Watch now'}</button></div><div className="hero-caption"><span>01</span> / YOUR COLLECTION</div></section>:null}
 <section className="collection"><div className="collection-heading"><div className="tabs"><button className={filter==='all'?'selected':''} onClick={()=>choose('all')}>All videos <span>{data.total}</span></button><button className={filter==='private'?'selected':''} onClick={()=>choose('private')}><LockKeyhole size={13}/> Private</button><button className={filter==='continue'?'selected':''} onClick={()=>choose('continue')}>In progress</button></div><div className="collection-actions"><select aria-label="Sort library" value={sort} onChange={e=>{setSort(e.target.value);setOffset(0);}}><option value="newest">Newest first</option><option value="oldest">Oldest first</option><option value="title">Title A–Z</option></select><button disabled={syncing||!data.connected} onClick={sync} className="sync"><RefreshCw size={15} className={syncing?'spinning':''}/>{syncing?'Syncing…':'Sync library'}</button></div></div><div className="collection-status" aria-live="polite"><span>{query?data.count+' results for “'+query+'”':data.channel?data.channel+' · '+data.count+' videos':'Your YouTube uploads will appear here'}</span><span>{syncing?checked+' videos checked':data.connected&&!data.complete?'Initial sync incomplete · Sync library to continue':data.synced?'Synced '+new Date(data.synced).toLocaleString():'Search covers titles and descriptions'}</span></div>
 {loading?<div className="grid" aria-label="Loading videos">{[1,2,3,4].map(n=><div className="skeleton" key={n}/>)}</div>:data.videos.length?<div className="grid">{data.videos.map(v=><button className="video-card" key={v.id} onClick={()=>setWatch(v)}><div className="poster"><img src={v.thumbnail} alt="" loading="lazy"/><span className="card-play"><Play size={24} fill="currentColor"/></span><span className="duration">{time(v.duration)}</span>{v.position>0&&v.position<v.duration-15&&<div className="progress"><span style={{width:Math.min(100,v.position/v.duration*100)+'%'}}/></div>}</div><h3>{v.title}</h3><div className="card-meta"><span>{new Date(v.published).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}</span><span>{v.privacy==='private'&&<LockKeyhole size={11}/>} {v.privacy}</span></div></button>)}</div>:data.connected?<div className="empty-results"><Library size={32}/><h3>{query?'No matching videos':filter==='continue'?'Your next watch starts here':data.complete?'No videos in this view':'Your library is ready to sync'}</h3><p>{query?'Try another title or a word from a description.':filter==='continue'?'Videos you start watching will appear here.':'Sync your uploads to refresh this collection.'}</p></div>:null}
 {data.count>24&&<div className="pagination"><button className="button secondary" disabled={offset===0||loading} onClick={()=>setOffset(n=>Math.max(0,n-24))}>Previous</button><span>{offset+1}–{Math.min(offset+24,data.count)} of {data.count}</span><button className="button secondary" disabled={offset+24>=data.count||loading} onClick={()=>setOffset(n=>n+24)}>Next</button></div>}</section><footer><span className="footer-brand">NOIR</span><span>Your collection. A little closer.</span><span><LockKeyhole size={12}/> Owner-only library · YouTube playback</span></footer>
 <dialog className="settings-dialog" ref={settingsDialog} onCancel={()=>setSettingsOpen(false)}><button className="icon-button close-settings" aria-label="Close settings" onClick={()=>setSettingsOpen(false)}><X/></button><span className="eyebrow">PRIVATE CONNECTION</span><h2>Your YouTube connection</h2><p>Manage credentials on your private site. Return here and reconnect afterward.</p><a className="button primary" href={BACKEND} target="_blank" rel="noopener noreferrer">Open private settings</a><p>Keep the connection window open while browsing. Close it or lock the library when finished.</p></dialog>
 {watch&&<Watch key={watch.id} video={watch} close={()=>{setWatch(null);setTimeout(()=>setRefresh(n=>n+1),500);}}/>}</main>;
}


