import {useCallback,useEffect,useRef,useState} from 'react';
import {Play,Pause,SkipBack,SkipForward,Maximize,Minimize,Volume2,VolumeX,X,Settings2,PictureInPicture2,RotateCcw} from 'lucide-react';
import {authorizePlayback,libraryFetch,playbackRequest} from './bridge-client';
import PlaybackAccount from './PlaybackAccount';
import {openBrowserStream} from './BrowserPlayback';
import {centeredTextFactory} from './CenteredSubtitles';
type Video={id:string;title:string;description:string;thumbnail:string;position:number;duration:number};
const languageName=(code:string)=>{try{return new Intl.DisplayNames([navigator.language],{type:'language'}).of(code)||code;}catch{return code;}};
const audioKey=(t:any)=>JSON.stringify([t.language,t.label,t.roles,t.codecs,t.channelsCount,t.spatialAudio]);
const clock=(value:number)=>{const t=Math.max(0,Math.floor(value||0));return (t>=3600?Math.floor(t/3600)+':':'')+String(Math.floor(t/60)%60).padStart(2,'0')+':'+String(t%60).padStart(2,'0');};
let enginePromise:Promise<any>|undefined;
function loadEngine(){return enginePromise??=new Promise((resolve,reject)=>{const script=document.createElement('script');script.src=new URL('./player-engine.js',document.baseURI).href;script.onload=()=>resolve((window as any).shaka);script.onerror=()=>{enginePromise=undefined;script.remove();reject(new Error('The player engine could not load. Retry playback.'));};document.head.appendChild(script);});}
export default function NoirPlayer({video,close}:{video:Video;close:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null),stage=useRef<HTMLDivElement>(null),element=useRef<HTMLVideoElement>(null),player=useRef<any>(null);
 const [attempt,setAttempt]=useState(0),[status,setStatus]=useState('Preparing your cinema…'),[error,setError]=useState(''),[connect,setConnect]=useState(false),[ready,setReady]=useState(false),[playing,setPlaying]=useState(false),[position,setPosition]=useState(video.position),[duration,setDuration]=useState(video.duration),[visible,setVisible]=useState(true),[settings,setSettings]=useState(false),[stats,setStats]=useState(false),[tracks,setTracks]=useState<any[]>([]),[texts,setTexts]=useState<any[]>([]),[quality,setQuality]=useState('auto'),[audio,setAudio]=useState(''),[audios,setAudios]=useState<any[]>([]),[caption,setCaption]=useState('off'),[rate,setRate]=useState('1'),[fit,setFit]=useState('contain'),[zoom,setZoom]=useState('1'),[volume,setVolume]=useState(1),[muted,setMuted]=useState(false),[fullscreen,setFullscreen]=useState(false),[metrics,setMetrics]=useState<any>({});
 const idle=useRef<ReturnType<typeof setTimeout>|undefined>(undefined),lastSaved=useRef(0);
 const retry=useCallback(()=>{setAttempt(n=>n+1);},[]);
 function reveal(){setVisible(true);clearTimeout(idle.current);if(playing&&!settings)idle.current=setTimeout(()=>{if(document.activeElement===stage.current||!stage.current?.contains(document.activeElement)||!document.activeElement?.matches(':focus-visible'))setVisible(false);},3500);}
 function toggle(){const v=element.current;if(v&&!v.paused)v.pause();else v?.play().catch(()=>setStatus('Press Play to begin.'));}
 function seek(seconds:number){const v=element.current;if(v)v.currentTime=Math.max(0,Math.min(v.duration||video.duration,seconds));reveal();}
 function full(){if(document.fullscreenElement)document.exitFullscreen().catch(()=>{});else stage.current?.requestFullscreen().catch(()=>setError('Fullscreen is unavailable in this browser.'));}
 useEffect(()=>{dialog.current?.showModal();const changed=()=>setFullscreen(!!document.fullscreenElement);document.addEventListener('fullscreenchange',changed);return()=>{clearTimeout(idle.current);document.removeEventListener('fullscreenchange',changed);};},[]);
 useEffect(()=>{if(!playing||settings)setVisible(true);else reveal();},[playing,settings]);
 useEffect(()=>{
  const controller=new AbortController();let active=true,local:any,timer:ReturnType<typeof setInterval>|undefined;setReady(false);setError('');setConnect(false);setStatus('Preparing your cinema…');setQuality('auto');setCaption('off');
  const refreshTracks=()=>{if(!active||!local)return;const variants=local.getVariantTracks();setTracks(variants);setTexts(local.getTextTracks());const a=local.getAudioTracks();setAudios(a);const selected=a.find((t:any)=>t.active)||a[0];setAudio(selected?audioKey(selected):'');};
  const save=()=>{const v=element.current;if(v&&Number.isFinite(v.currentTime)&&v.currentTime>0)void libraryFetch('/api/library',{method:'POST',headers:{'Content-Type':'application/json','X-Noir-Request':'1'},body:JSON.stringify({action:'progress',id:video.id,seconds:v.currentTime})}).catch(()=>{});};
  (async()=>{try{
   const account=await playbackRequest('account',undefined,controller.signal);if(!active)return;if(!account.available)throw new Error('The new Cloudflare playback service is not deployed yet.');if(!account.connected){setConnect(true);setStatus('One connection. Every private upload.');return;}
   const engine=await loadEngine();if(!active)return;engine.polyfill.installAll();if(!engine.Player.isBrowserSupported())throw new Error('This browser does not support adaptive video playback. Try an updated browser.');
   local=new engine.Player();player.current=local;await local.attach(element.current);if(!active)return;
   local.setVideoContainer(stage.current);
   local.configure({textDisplayFactory:centeredTextFactory(local.getConfiguration().textDisplayFactory,engine),streaming:{bufferingGoal:30,rebufferingGoal:2,bufferBehind:5},abr:{enabled:true},manifest:{dash:{ignoreMinBufferTime:true}}});
   local.getNetworkingEngine().registerRequestFilter((_type:any,request:any)=>{authorizePlayback(request.uris,request.headers);request.allowCrossSiteCredentials=false;});
   local.addEventListener('error',()=>{if(active){setError('The stream stopped or your connection expired. Retry to request fresh playback.');setStatus('Playback interrupted');}});
   local.addEventListener('trackschanged',refreshTracks);local.addEventListener('variantchanged',refreshTracks);local.addEventListener('adaptation',refreshTracks);
   setStatus('Opening your private stream…');const source=await openBrowserStream(video.id,controller.signal);if(!active)return;
   const resume=element.current?.currentTime||video.position;await local.load(source.manifest,resume<video.duration-15?resume:0,'application/dash+xml');if(!active)return;
   refreshTracks();setReady(true);setStatus('');const v=element.current!;v.playbackRate=Number(rate);v.volume=volume;v.muted=muted;await v.play().catch(()=>{if(active)setStatus('Press Play to begin.');});
   timer=setInterval(()=>{if(active){setMetrics(local.getStats());if(v.currentTime-lastSaved.current>=15||lastSaved.current-v.currentTime>=15){lastSaved.current=v.currentTime;save();}}},1000);
  }catch(e){if(active&&!controller.signal.aborted){setError((e as Error).message);setStatus('Your cinema will be ready shortly.');}}})();
  return()=>{active=false;controller.abort();clearInterval(timer);save();if(player.current===local)player.current=null;void local?.destroy();};
 },[video.id,attempt]);
 useEffect(()=>{const v=element.current;if(v){v.playbackRate=Number(rate);v.volume=volume;v.muted=muted;}},[rate,volume,muted,ready]);
 function selectQuality(id:string){setQuality(id);const p=player.current;if(!p)return;p.configure({abr:{enabled:id==='auto'}});if(id!=='auto'){const track=p.getVariantTracks().find((t:any)=>String(t.id)===id);if(track)p.selectVariantTrack(track,true);}}
 function selectAudio(key:string){setAudio(key);setQuality('auto');const p=player.current,t=audios.find(t=>audioKey(t)===key);if(p&&t){p.configure({abr:{enabled:true}});p.selectAudioTrack(t);}}
 const activeTrack=tracks.find(t=>t.active),videoTracks=tracks.filter(t=>!activeTrack||t.audioId===activeTrack.audioId).sort((a,b)=>b.height-a.height||b.bandwidth-a.bandwidth);

 const qualityLabel=(t:any)=>`${t.height||'?'}p${t.height>=2160?' · 4K':''} · ${t.videoCodec?.split('.')[0]||''}${t.frameRate>30?' · '+Math.round(t.frameRate)+'fps':''}`;
 return <dialog className="noir-watch" ref={dialog} onCancel={close} aria-label={'Playing '+video.title}>
  <div className={'noir-stage '+(!visible?'controls-hidden':'')} ref={stage} onPointerMove={reveal} onPointerDown={reveal} onFocusCapture={()=>{setVisible(true);clearTimeout(idle.current);}} onKeyDown={e=>{if((e.target as HTMLElement).matches('input,select,button,a'))return;const key=e.key.toLowerCase();if([' ','arrowleft','arrowright','f','m'].includes(key))e.preventDefault();if(key===' ')toggle();if(key==='arrowleft')seek(position-10);if(key==='arrowright')seek(position+10);if(key==='f')full();if(key==='m')setMuted(m=>!m);reveal();}} tabIndex={0}>
   <video ref={element} className={'noir-video '+(fit.startsWith('ratio')?'fixed-ratio':'')} poster={video.thumbnail||undefined} playsInline style={{objectFit:fit==='cover'?'cover':fit==='fill'?'fill':'contain',transform:`scale(${zoom})`,aspectRatio:fit==='ratio43'?'4 / 3':fit==='ratio219'?'21 / 9':'16 / 9'}} onClick={toggle} onDoubleClick={full} onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onTimeUpdate={e=>setPosition(e.currentTarget.currentTime)} onDurationChange={e=>{if(Number.isFinite(e.currentTarget.duration))setDuration(e.currentTarget.duration);}} onWaiting={()=>ready&&setStatus('Buffering…')} onPlaying={()=>setStatus('')} onEnded={()=>{setPlaying(false);setStatus('Finished. Your place is saved.');}}/>
   <div className="noir-player-top"><div><span className="eyebrow">NOIR / NOW PLAYING</span><h2>{video.title}</h2></div><button aria-label="Close player" onClick={close}><X/></button></div>
   {(status||error||connect)&&<div className="noir-player-message" aria-live="polite">{connect?<PlaybackAccount onConnected={retry}/>:<><span className="eyebrow">YOUR PRIVATE CINEMA</span><h3>{error?'Let’s reconnect.':status}</h3>{error?<><p role="alert">{error}</p><button className="button primary" onClick={retry}><RotateCcw size={17}/> Retry playback</button></>:ready?<button className="button primary" onClick={toggle}><Play size={17}/> {playing?'Continue':'Play'}</button>:<div className="loading-line"/>}</>}</div>}
   <div className="noir-controls"><div className="seek-row"><span>{clock(position)}</span><input aria-label="Video position" type="range" min={0} max={duration||1} step={0.1} value={Math.min(position,duration||1)} disabled={!ready} onChange={e=>seek(Number(e.target.value))}/><span>{clock(duration)}</span></div><div className="noir-transport"><button className="play-control" disabled={!ready} aria-label={playing?'Pause':'Play'} onClick={toggle}>{playing?<Pause fill="currentColor"/>:<Play fill="currentColor"/>}</button><button disabled={!ready} aria-label="Back 10 seconds" onClick={()=>seek(position-10)}><SkipBack/></button><button disabled={!ready} aria-label="Forward 10 seconds" onClick={()=>seek(position+10)}><SkipForward/></button><button aria-label={muted?'Unmute':'Mute'} onClick={()=>setMuted(m=>!m)}>{muted||volume===0?<VolumeX/>:<Volume2/>}</button><input className="volume-control" aria-label="Volume" type="range" min={0} max={1} step={0.05} value={muted?0:volume} onChange={e=>{setVolume(+e.target.value);setMuted(false);}}/><span className="stream-badge">{ready?(activeTrack?.height?activeTrack.height+'p · ':'')+(quality==='auto'?'AUTO':'SELECTED'):'PRIVATE STREAM'}</span><button aria-label="Player settings" aria-expanded={settings} onClick={()=>setSettings(s=>!s)}><Settings2/></button>{document.pictureInPictureEnabled&&<button aria-label="Picture in picture" disabled={!ready} onClick={()=>{const v=element.current;if(document.pictureInPictureElement)document.exitPictureInPicture().catch(()=>{});else v?.requestPictureInPicture().catch(()=>setError('Picture in picture is unavailable for this stream.'));}}><PictureInPicture2/></button>}<button aria-label={fullscreen?'Exit fullscreen':'Fullscreen'} onClick={full}>{fullscreen?<Minimize/>:<Maximize/>}</button></div></div>
   {settings&&<section className="noir-player-settings" aria-label="Playback settings"><div className="settings-heading"><span className="eyebrow">MAKE IT YOUR CINEMA</span><button onClick={()=>setSettings(false)} aria-label="Close player settings"><X size={18}/></button></div><label>Video quality<select disabled={!ready} value={quality} onChange={e=>selectQuality(e.target.value)}><option value="auto">Auto · adapts to your connection</option>{videoTracks.map(t=><option value={t.id} key={t.id}>{qualityLabel(t)}</option>)}</select></label><label>Audio<select disabled={!ready} value={audio} onChange={e=>selectAudio(e.target.value)}>{audios.map(t=><option key={audioKey(t)} value={audioKey(t)}>{t.label||(t.language==='und'?'Original audio':languageName(t.language))}{t.codecs?' · '+t.codecs.split('.')[0]:''}{t.channelsCount>2?' · '+t.channelsCount+'ch':''}</option>)}</select></label><label>Subtitles<select disabled={!ready||!texts.length} value={caption} onChange={e=>{setCaption(e.target.value);const p=player.current;p?.selectTextTrack(e.target.value==='off'?null:texts.find(t=>String(t.id)===e.target.value));}}><option value="off">Off{texts.length?'':' · none available'}</option>{texts.map(t=><option key={t.id} value={t.id}>{t.label||languageName(t.language)}</option>)}</select></label><div className="settings-pair"><label>Speed<select value={rate} onChange={e=>setRate(e.target.value)}>{[0.5,0.75,1,1.25,1.5,1.75,2].map(n=><option key={n} value={n}>{n}×</option>)}</select></label><label>Zoom<select value={zoom} onChange={e=>setZoom(e.target.value)}>{[1,1.1,1.25,1.5,2].map(n=><option key={n} value={n}>{Math.round(n*100)}%</option>)}</select></label></div><label>Picture fit<select value={fit} onChange={e=>setFit(e.target.value)}><option value="contain">Original · fit</option><option value="cover">Fill · crop edges</option><option value="fill">Stretch to screen</option><option value="ratio43">4:3 · fit</option><option value="ratio219">21:9 · fit</option></select></label><button className="button secondary" onClick={()=>setStats(s=>!s)}>{stats?'Hide':'Show'} stream details</button><p>Quality, codecs and audio tracks depend on the upload and what your browser can decode.</p></section>}
   {stats&&ready&&<div className="noir-stats">{metrics.width}×{metrics.height} · {activeTrack?.videoCodec||'—'} / {activeTrack?.audioCodec||'—'}<br/>{Math.round((metrics.estimatedBandwidth||0)/1e6*10)/10} Mbps available · {metrics.droppedFrames||0} frames dropped<br/>Buffering waits: {Math.round(metrics.bufferingTime||0)}s total · speed {rate}×</div>}
  </div><div className="noir-film-notes"><span className="eyebrow">FROM YOUR COLLECTION</span><p className="description">{video.description||'No description added.'}</p><small>Space: play / pause · ← →: seek · F: fullscreen · M: mute</small></div>
 </dialog>;
}
